// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

// For Prisma 5, configuration is handled via environment variables
// No need for a defineConfig in this version
